/**
 * data.js - قاعدة البيانات وتهيئة الربط السحابي مع Firebase Firestore
 * المشروع: toti-ae62c
 */

// تهيئة إعدادات Firebase الخاصة بمشروعك
const firebaseConfig = {
  apiKey: "AIzaSyDR4KcHKSIxRGzrFmkJ536j9pPGLzo18-k",
  authDomain: "toti-ae62c.firebaseapp.com",
  projectId: "toti-ae62c",
  storageBucket: "toti-ae62c.firebasestorage.app",
  messagingSenderId: "42863617740",
  appId: "1:42863617740:web:e1ad90b5b8ab752c84c469",
  measurementId: "G-YYVRCKPMQR",
};

// تشغيل Firebase وربط Firestore
if (typeof firebase !== "undefined" && !firebase.apps.length) {
  firebase.initializeApp(firebaseConfig);
  window.dbFirestore = firebase.firestore();
}

window.db = {
  // 1. قائمة المعايير والمهام الـ 29 المعتمدة كقوالب جاهزة للتكليف[cite: 18]
  taskTemplates: [
    "أن يقوم مسؤول شؤون الطلاب بنفسه بالتحضير الأسبوعي",
    "أن يتضمن التحضير الأسبوعي فرز لنوع الغياب (بعذر / بدون عذر)",
    "إبلاغ مشرفي الحلقات والمجمعات القرآنية بانضباط طلابهم بالحضور الأسبوعي",
    "أن تتواصل إدارة البرنامج مع الطلاب المتغيبين بدون عذر",
    "أن يسلم الشرح قبل أول يوم من أيام الدرس الأسبوعي",
    "أن يسلم للطلاب جدول قراءة الشرح قبل 5 أيام من بداية الدرس الأسبوعي",
    "أن يذكر الطلاب بقراءة المقدار الأسبوعي للمتن في المجموعة الطلابية قبل الدرس",
    "أن يذكر الطلاب بقراءة المقدار الأسبوعي للشرح في المجموعة الطلابية بعد الدرس",
    "أن يرصد إنجاز الطلاب في القراءة القبلية للمتن والشرح",
    "أن تعد إدارة البرنامج السؤال الأسبوعي ويكون متعلق بما تم شرحه في هذا الأسبوع",
    "أن يكرم في كل أسبوع الفائز بالسؤال الأسبوعي",
    "أن يكرم المتميزين في أداء القراءة وعدم الغياب بعد آخر درس مباشرة",
    "أن يتم تنفيذ ساعات المقرر وفق الخطة العلمية",
    "أن يتم التنسيق مع ملقي مناسب قبل بداية الدرس الأسبوعي بمدة لا تقل عن أسبوع",
    "أن يصل توصيف المقرر للملقي",
    "أن يصل تقسيم المقرر للملقي",
    "أن يتابع الملقي أسبوعياً في إنجاز المقرر الأسبوعي المحدد",
    "استخدام الملقي للأدوات التعليمية المساندة وتفعيله لها أثناء الإلقاء",
    "أن يتم تقييم الملقي بعد انتهاء الدرس الأسبوعي",
    "أن يتم رصد مدى رضا الملقي عن الدرس الأسبوعي",
    "أن يكون الحد الأعلى لوقت الدرس 90 دقيقة والحد الأدنى 60 دقيقة",
    "أن يكون الدرس الأسبوعي حضورياً بنسبة 80% ولا يصار إلى تنفيذه عن بعد إلا عند الظروف الاستثنائية",
    "أن تكون أسئلة الاختبار متنوعة بين المقالي والموضوعي على أن تكون نسبة الأسئلة المقالية 30% من الاختبار",
    "أن يقام اختبار الدرس الأسبوعي حضورياً",
    "أن يقام الاختبار النهائي بعد آخر درس بمدة لا تقل عن 4 أيام ولا تزيد عن 7 أيام",
    "أن يتم إجراء اختبار بديل للمتغيبين والراسبين بعد الاختبار الأساسي للدرس الأسبوعي",
    "أن يبلغ الطلاب ومشرفي الحلقات بدرجات الاختبار",
    "أن يكون مكان الدرس الأسبوعي مهيئاً بالأدوات التعليمية المساندة (سبورة - شاشة - سماعات - بروجكتر)",
    "أن يتم رصد مدى رضا الطلاب عن الدرس الأسبوعي",
  ],

  // 2. برامج المنصة الأساسية (بدون ال التعريف)[cite: 18]
  programs: [
    {
      id: "prog_taheel",
      name: "تأهيل",
      color: "#169BA2",
      levelsCount: 2,
    },
    {
      id: "prog_taseel",
      name: "تأصيل",
      color: "#0B2533",
      levelsCount: 3,
    },
    {
      id: "prog_rasookh",
      name: "رسوخ",
      color: "#D4A359",
      levelsCount: 2,
    },
  ],

  // 3. مستويات البرامج[cite: 18]
  levels: [
    {
      id: "lvl_th_1",
      programId: "prog_taheel",
      name: "المستوى الأول - تأسيس",
      order: 1,
    },
    {
      id: "lvl_th_2",
      programId: "prog_taheel",
      name: "المستوى الثاني - تمكين",
      order: 2,
    },
    {
      id: "lvl_ts_1",
      programId: "prog_taseel",
      name: "المستوى الأول - أصول وتمهيد",
      order: 1,
    },
    {
      id: "lvl_ts_2",
      programId: "prog_taseel",
      name: "المستوى الثاني - تأصيل وتعميق",
      order: 2,
    },
    {
      id: "lvl_ts_3",
      programId: "prog_taseel",
      name: "المستوى الثالث - إتقان وبحث",
      order: 3,
    },
    {
      id: "lvl_rs_1",
      programId: "prog_rasookh",
      name: "المستوى المتقدم الأول",
      order: 1,
    },
    {
      id: "lvl_rs_2",
      programId: "prog_rasookh",
      name: "المستوى المتقدم الثاني",
      order: 2,
    },
  ],

  // 4. المجموعات الدراسية[cite: 18]
  groups: [
    {
      id: "grp_ts_101",
      levelId: "lvl_ts_1",
      programId: "prog_taseel",
      name: "مجموعة الخليل بن أحمد",
      supervisorId: "supervisor_1",
    },
    {
      id: "grp_rs_201",
      levelId: "lvl_rs_1",
      programId: "prog_rasookh",
      name: "مجموعة الشاطبي المتقدمة",
      supervisorId: "supervisor_1",
    },
    {
      id: "grp_th_001",
      levelId: "lvl_th_1",
      programId: "prog_taheel",
      name: "مجموعة البخاري التأسيسية",
      supervisorId: "supervisor_2",
    },
    {
      id: "grp_ts_102",
      levelId: "lvl_ts_1",
      programId: "prog_taseel",
      name: "مجموعة سيبويه التأصيلية",
      supervisorId: "supervisor_3",
    },
  ],

  // 5. المستخدمين والحسابات[cite: 18]
  users: [
    {
      id: "admin",
      name: "إدارة المنصة المركزية",
      role: "admin",
      phone: "0500000000",
      password: "1234",
      email: "admin@alelm.edu.sa",
      avatar: "إد",
      color: "#0B2533",
      isRestricted: false,
    },
    {
      id: "supervisor_1",
      name: "أ. أحمد الميموني",
      role: "supervisor",
      phone: "0551112233",
      password: "1234",
      email: "ahmed@alelm.edu.sa",
      avatar: "أح",
      color: "#169BA2",
      assignedPrograms: ["prog_taseel", "prog_rasookh"],
      assignedGroups: ["grp_ts_101", "grp_rs_201"],
      isRestricted: false,
    },
    {
      id: "supervisor_2",
      name: "أ. فيصل السعيد",
      role: "supervisor",
      phone: "0554445566",
      password: "1234",
      email: "faisal@alelm.edu.sa",
      avatar: "في",
      color: "#E59824",
      assignedPrograms: ["prog_taheel"],
      assignedGroups: ["grp_th_001"],
      isRestricted: false,
    },
    {
      id: "supervisor_3",
      name: "أ. سعد الغامدي",
      role: "supervisor",
      phone: "0557778899",
      password: "1234",
      email: "saad@alelm.edu.sa",
      avatar: "سع",
      color: "#8AA838",
      assignedPrograms: ["prog_taseel"],
      assignedGroups: ["grp_ts_102"],
      isRestricted: false,
    },
    {
      id: "student_1",
      name: "عبد الله العتيبي",
      role: "student",
      studentNumber: "STU-2026-001",
      phone: "0550011223",
      fatherPhone: "0500011223",
      password: "1234",
      email: "abdullah@gmail.com",
      avatar: "عب",
      currentProgramId: "prog_taseel",
      currentLevelId: "lvl_ts_1",
      groupId: "grp_ts_101",
      supervisorId: "supervisor_1",
      progress: 78,
      isRestricted: false,
    },
    {
      id: "student_2",
      name: "محمد الشهري",
      role: "student",
      studentNumber: "STU-2026-002",
      phone: "0553344556",
      fatherPhone: "0503344556",
      password: "1234",
      email: "m.shehri@gmail.com",
      avatar: "مح",
      currentProgramId: "prog_taseel",
      currentLevelId: "lvl_ts_1",
      groupId: "grp_ts_101",
      supervisorId: "supervisor_1",
      progress: 45,
      isRestricted: false,
    },
    {
      id: "student_3",
      name: "خالد الغامدي",
      role: "student",
      studentNumber: "STU-2026-003",
      phone: "0556677889",
      fatherPhone: "0506677889",
      password: "1234",
      email: "khaled@gmail.com",
      avatar: "خا",
      currentProgramId: "prog_rasookh",
      currentLevelId: "lvl_rs_1",
      groupId: "grp_rs_201",
      supervisorId: "supervisor_1",
      progress: 92,
      isRestricted: false,
    },
  ],

  // 6. طلبات التسجيل الجديدة[cite: 18]
  registrationRequests: [
    {
      id: "req_101",
      name: "ياسر القحطاني",
      phone: "0558899001",
      fatherPhone: "0508899001",
      programId: "prog_taseel",
      requestDate: "2026-08-28",
      status: "قيد المراجعة",
    },
    {
      id: "req_102",
      name: "بدر عسيري",
      phone: "0552233445",
      fatherPhone: "0502233445",
      programId: "prog_taheel",
      requestDate: "2026-08-29",
      status: "قيد المراجعة",
    },
  ],

  // 7. طلبات تعديل البيانات المقدمة للاعتماد[cite: 18]
  pendingProfileEdits: [
    {
      id: "edit_101",
      studentId: "student_1",
      studentName: "عبد الله العتيبي",
      newPhone: "0550099887",
      newFatherPhone: "0500099887",
      newEmail: "abdullah.new@gmail.com",
      requestDate: "2026-08-29",
      status: "بانتظار الاعتماد",
    },
  ],

  // 8. سجل مشاركات الطلاب في البرامج[cite: 18]
  studentPrograms: [
    {
      id: "sp_1",
      studentId: "student_1",
      programId: "prog_taseel",
      status: "مستمر",
      startDate: "2026-01-15",
      endDate: null,
    },
    {
      id: "sp_2_old",
      studentId: "student_2",
      programId: "prog_taheel",
      status: "مكتمل",
      startDate: "2025-09-01",
      endDate: "2026-01-10",
    },
    {
      id: "sp_2_curr",
      studentId: "student_2",
      programId: "prog_taseel",
      status: "مستمر",
      startDate: "2026-01-15",
      endDate: null,
    },
    {
      id: "sp_3",
      studentId: "student_3",
      programId: "prog_rasookh",
      status: "مستمر",
      startDate: "2026-02-01",
      endDate: null,
    },
  ],

  // 9. مسار التاريخ التعليمي للطالب[cite: 18]
  studentPaths: [
    {
      studentId: "student_1",
      history: [
        {
          programName: "تأصيل",
          status: "مستمر",
          period: "2026 - الحالي",
          isCurrent: true,
        },
      ],
    },
    {
      studentId: "student_2",
      history: [
        {
          programName: "تأهيل",
          status: "مكتمل",
          period: "2025 - 2026",
          isCurrent: false,
        },
        {
          programName: "تأصيل",
          status: "مستمر",
          period: "2026 - الحالي",
          isCurrent: true,
        },
      ],
    },
    {
      studentId: "student_3",
      history: [
        {
          programName: "رسوخ",
          status: "مستمر",
          period: "2026 - الحالي",
          isCurrent: true,
        },
      ],
    },
  ],

  // 10. عناصر الجدول الأسبوعي[cite: 18]
  schedules: [
    {
      id: "sch_ts_1",
      programId: "prog_taseel",
      groupId: "grp_ts_101",
      dayOfWeek: 0,
      time: "05:00 م",
      title: "درس أصول الفقه - الوحدة الأولى",
      type: "lesson",
      typeLabel: "درس",
      status: "قادم",
      requiresAttendance: true,
      details: "قراءة الباب الأول وتحضير أسئلة المناقشة.",
    },
    {
      id: "sch_ts_2",
      programId: "prog_taseel",
      groupId: "grp_ts_101",
      dayOfWeek: 2,
      time: "06:30 م",
      title: "لقاء المدارسة التفاعلي",
      type: "meeting",
      typeLabel: "لقاء",
      status: "قادم",
      requiresAttendance: true,
      details: "حضور اللقاء التفاعلي مع أ. أحمد الميموني عبر القاعة الرقمية.",
    },
    {
      id: "sch_ts_3",
      programId: "prog_taseel",
      groupId: "grp_ts_101",
      dayOfWeek: 3,
      time: "07:00 م",
      title: "اختبار منتصف البرنامج",
      type: "exam",
      typeLabel: "اختبار",
      status: "قادم",
      requiresAttendance: false,
      details: "اختبار تحصيلي إلكتروني يحتوي 20 سؤال اختيار من متعدد.",
    },
    {
      id: "sch_th_1",
      programId: "prog_taheel",
      groupId: "grp_th_001",
      dayOfWeek: 1,
      time: "04:30 م",
      title: "مدخل البناء العلمي والتأسيس",
      type: "lesson",
      typeLabel: "درس",
      status: "قادم",
      requiresAttendance: true,
      details: "شرح المقدمة المنهجية لطلاب التأهيل.",
    },
    {
      id: "sch_th_2",
      programId: "prog_taheel",
      groupId: "grp_th_001",
      dayOfWeek: 4,
      time: "05:00 م",
      title: "حلقة مدارسة التلاوة وضبط الأداء",
      type: "lesson",
      typeLabel: "نشاط",
      status: "قادم",
      requiresAttendance: true,
      details: "تطبيق أحكام التجويد ومخارج الحروف.",
    },
    {
      id: "sch_rs_1",
      programId: "prog_rasookh",
      groupId: "grp_rs_201",
      dayOfWeek: 0,
      time: "07:30 م",
      title: "حلقة التحليل والتمكين المتقدم",
      type: "meeting",
      typeLabel: "لقاء",
      status: "قادم",
      requiresAttendance: true,
      details: "مناقشة أبحاث التخرج وقضايا الخلاف العالي.",
    },
    {
      id: "sch_rs_2",
      programId: "prog_rasookh",
      groupId: "grp_rs_201",
      dayOfWeek: 6,
      time: "06:00 م",
      title: "التقييم الأسبوعي ومقياس الرسوخ",
      type: "assessment",
      typeLabel: "تقييم",
      status: "قادم",
      requiresAttendance: false,
      details: "مراجعة المؤشرات المهارية والبحثية.",
    },
  ],

  // 11. سجلات الحضور والتحضير[cite: 18]
  attendanceRecords: [
    {
      id: "att_1",
      scheduleId: "sch_ts_1",
      studentId: "student_1",
      status: "حاضر",
      updatedAt: "2026-08-23 05:10 م",
      recordedBy: "supervisor_1",
    },
  ],

  // 12. سجل المهام والتكليفات[cite: 18]
  tasks: [
    {
      id: "tsk_201",
      title: "أن يقوم مسؤول شؤون الطلاب بنفسه بالتحضير الأسبوعي",
      programId: "prog_taseel",
      dayOfWeek: 0,
      date: "2026-08-30",
      startTime: "04:30 م",
      endTime: "06:00 م",
      assigneeRole: "supervisor",
      assignedTo: "supervisor_1",
      status: "قيد التنفيذ",
      completedAt: null,
      delegatedFrom: null,
      isRecurring: true,
      recurringDays: [0],
      stopDate: "2026-11-30",
      requiresAttendance: true,
      isExempt: false,
      exemptionReason: null,
      createdBy: "admin",
      description: "التحضير المسبق وتدوين مداخلات الطلاب ومتابعة نسبة الفهم.",
    },
    {
      id: "tsk_202",
      title:
        "أن تعد إدارة البرنامج السؤال الأسبوعي ويكون متعلق بما تم شرحه في هذا الأسبوع",
      programId: "prog_taseel",
      dayOfWeek: 0,
      date: "2026-08-30",
      startTime: "07:00 م",
      endTime: "08:30 م",
      assigneeRole: "supervisor",
      assignedTo: "supervisor_3",
      status: "مكتملة",
      completedAt: "2026-08-29 08:15 م",
      delegatedFrom: null,
      isRecurring: false,
      requiresAttendance: false,
      isExempt: false,
      exemptionReason: null,
      createdBy: "admin",
      description: "إعداد السؤال الأسبوعي واعتماد نموذج الإجابة الصحيحة.",
    },
    {
      id: "tsk_203",
      title: "أن تتواصل إدارة البرنامج مع الطلاب المتغيبين بدون عذر",
      programId: "prog_taseel",
      dayOfWeek: 2,
      date: "2026-09-01",
      startTime: "06:00 م",
      endTime: "07:00 م",
      assigneeRole: "supervisor",
      assignedTo: "supervisor_1",
      status: "معفى بعذر",
      completedAt: null,
      delegatedFrom: null,
      isRecurring: false,
      requiresAttendance: false,
      isExempt: true,
      exemptionReason: "عذر رسمي لانتداب خارجي معتمد من الإدارة.",
      createdBy: "admin",
      description: "التواصل الهاتفي المباشر مع أولياء أمور الطلاب المتغيبين.",
    },
    {
      id: "tsk_204",
      title:
        "أن يسلم للطلاب جدول قراءة الشرح قبل 5 أيام من بداية الدرس الأسبوعي",
      programId: "prog_taheel",
      dayOfWeek: 1,
      date: "2026-08-31",
      startTime: "05:00 م",
      endTime: "06:30 م",
      assigneeRole: "supervisor",
      assignedTo: "supervisor_2",
      status: "لم تبدأ",
      completedAt: null,
      delegatedFrom: null,
      isRecurring: false,
      requiresAttendance: true,
      isExempt: false,
      exemptionReason: null,
      createdBy: "admin",
      description: "إرسال الجداول بصيغة PDF للطلاب في المجموعة المعتمدة.",
    },
    {
      id: "tsk_101",
      title:
        "أن يذكر الطلاب بقراءة المقدار الأسبوعي للمتن في المجموعة الطلابية قبل الدرس",
      programId: "prog_taseel",
      dayOfWeek: 1,
      date: "2026-08-31",
      startTime: "08:00 ص",
      endTime: "11:59 م",
      assigneeRole: "student",
      assignedTo: "student_1",
      status: "قيد التنفيذ",
      completedAt: null,
      delegatedFrom: null,
      isRecurring: false,
      requiresAttendance: false,
      isExempt: false,
      exemptionReason: null,
      createdBy: "admin",
      description: "التأكد من قراءة المقرر المحدد قبل الحضور.",
    },
  ],

  // 13. لوحة الإعلانات العامة[cite: 18]
  announcements: [
    {
      id: "anc_1",
      title: "بدء فتح رصد تحضير الجلسات وحلقات المدارسة",
      content:
        "نحيط جميع المشرفين الكرام بأنه تم تفعيل خانات التحضير للمهام والجلسات المحددة في الجدول الأسبوعي. يرجى المبادرة برصد حضور الطلاب في وقت الجلسة.",
      publisher: "إدارة المنصة المركزية",
      targetGroup: "supervisors",
      mediaType: "image",
      mediaUrl: "logo16.png",
      date: "2026-08-28",
      expiresAt: "2026-09-15",
      priority: "عاجل",
    },
    {
      id: "anc_2",
      title: "مواعيد اختبارات منتصف برنامج التأصيل",
      content:
        "تقرر عقد الاختبار النصفي لطلاب برنامج التأصيل يوم الأربعاء القادم في تمام الساعة 07:00 مساءً إلكترونياً عبر بوابة الاختبارات.",
      publisher: "أ. أحمد الميموني (مشرف التأصيل)",
      targetGroup: "prog_taseel",
      mediaType: "none",
      mediaUrl: "",
      date: "2026-08-27",
      expiresAt: "2026-09-05",
      priority: "عادي",
    },
  ],

  // 14. التنبيهات والإشعارات[cite: 18]
  notifications: [
    {
      id: "notif_101",
      userId: "admin",
      category: "إشعار إداري",
      title: "طلب تسجيل جديد",
      message: "قام الطالب بدر عسيري بتقديم طلب التحاق ببرنامج التأهيل.",
      date: "قبل 15 دقيقة",
      isRead: false,
    },
    {
      id: "notif_102",
      userId: "supervisor_1",
      category: "تذكير بمهمة",
      title: "تذكير بمهمة قادمة",
      message: "لديك مهمة معيارية مجدولة ليوم الأحد القادم.",
      date: "قبل ساعة",
      isRead: false,
    },
  ],
};
